name: ci + cd demo workflow

# define when the workflow should run/ On a push to main, a PR to main or manually with workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch: 

# Define some jobs that should run/

jobs:
  Build:
    runs-on: ubuntu_latest
    steps:
      - uses: actions/checkout@v3
      - name: compile
        run: echo compiling our code
			  
  DeployDev:
    name: deploy to dev
    if: github.event_name == 'pull_request'
    needs: [Build]
    runs-on: ubuntu_latest
    environment:
      name: dev
      url: 'http://dev.myapp.com'
    steps:
    - name: Deploy
      run: echo deploying our code to dev
 
# deploy to staging
  DeployStaging:
    name: deploy to staging
    if: github.event.ref == 'refs/heads/main'
    needs: [Build]
    runs-on: ubuntu_latest
    environment:
      name: staging
      url: 'http://staging.myapp.com'
    steps:
    - name: Deploy
      run: echo deploying our code to staging
			  
# deploy to production
  DeployProd:
    name: deploy to production
    needs: [DeployStaging]
    runs-on: ubuntu_latest
    environment:
      name: prod
      url: 'http://prod.myapp.com'
    steps:
    - name: Deploy
      run: echo deploying our code to production
